main: org.zkaleejoo.OnlyClans
version: 1.0.0
name: OnlyClans
author: ZkAleeJoo
api-version: '1.21'
folia-supported: true

commands:
  onlyclans:
    description: Main command for OnlyClans
    aliases: [clan, clans]
  clanchat:
    description: Send a message to your clan chat
    aliases: [c, cc]

permissions:
  onlyclans.admin:
    description: Full access to admin commands.
    default: op
  onlyclans.use:
    description: Access to basic clan commands.
    default: true
